version: '3'
services:
  db_postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - '5432:5432'
    volumes:
      - /home/legend/db_task:/var/lib/postgresql/data
volumes:
  db:
    driver: local