openapi: 3.0.0
info:
  version: 1.0.0
  title: taskmanager
servers:
  - url: 'http://localhost:3000'
paths:
  /tasks:
    post:
      summary: 'creates a task'
      operationId: createTask
      tags:
        - task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

  /tasks/{id}:
    get:
      summary: 'Return a Task by ID'
      operationId: getTask
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the task
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        404:
          description: Not Found

    put:
      summary: 'Update a Task By ID'
      operationId: updateTask
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          description: id of the task
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskDTO'
        required: true
      responses:
        204:
          description: 'Updated Successfully'
        404:
          description: 'Not Found'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

    delete:
      summary: 'Deletes a task by ID'
      operationId: deleteTask
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the task
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: 'Deleted Successfully'
        404:
          description: Not Found

  /users:
    post:
      summary: 'Creates an User'
      operationId: createUser
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        404:
          description: 'Not Found'

    put:
      summary: 'Updates User data'
      operationId: updateUser
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          description: id of the task
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDTO'
        required: true
      responses:
        204:
          description: 'Updated Successfully'
        404:
          description: 'Not Found'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

  /users/{id}:
    get:
      summary: 'Return an User by ID'
      operationId: getUser
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        404:
          description: Not Found

components:
  schemas:
    UpdateTaskDTO:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        finishAt:
          type: string
          format: date-time

    CreateTaskDTO:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        finishAt:
          type: string
          format: date-time
        userId:
          type: string
          format: uuid

    TaskDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateTaskDTO'
        - type: object
          properties:
            id:
              type: string
              format: uuid
            isFinished:
              type: boolean
            createdAt:
              type: string
              format: date-time

    UpdateUserDTO:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    CreateUserDTO:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    UserDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/UpdateUserDTO'
        - type: object
          properties:
            id:
              type: string
              format: uuid
            tasks:
              type: array
              items:
                $ref: '#/components/schemas/TaskDTO'

    ResponseError:
      type: object
      required:
        - field
        - errorCode
      properties:
        field:
          type: string
        errorCode:
          type: string

  responses:
    UnprocessableEntity:
      description: The server understands the content type of the request entity but was unable to process
        the contained instructions.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ResponseError'